# Generated by Django 4.0.4 on 2022-05-02 03:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0015_alter_quiz_created_at_alter_quiz_difficulty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quiz',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('difficult', 'difficult'), ('medium', 'medium'), ('easy', 'easy')], max_length=20),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='grade',
            field=models.CharField(blank=True, choices=[('2nd Grade', '2nd Grade'), ('Pre-K', 'Pre-K'), ('3rd Grade', '3rd Grade'), ('1st Grade', '1st Grade'), ('Kindergarten', 'Kindergarten')], max_length=50),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='subject',
            field=models.CharField(blank=True, choices=[('Science', 'Science'), ('Korean', 'Korean'), ('Math', 'Math'), ('Spanish', 'Spanish'), ('English', 'English'), ('Social Studies', 'Social Studies')], max_length=20),
        ),
    ]
