# Generated by Django 4.0.4 on 2022-05-01 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.CharField(choices=[('Kindergarten', 'Kindergarten'), ('Pre-K', 'Pre-K'), ('3rd Grade', '3rd Grade'), ('1st Grade', '1st Grade'), ('2nd Grade', '2nd Grade')], max_length=50),
        ),
        migrations.AlterField(
            model_name='takenquiz',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
