# Generated by Django 4.0.4 on 2022-04-22 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_student_grade_alter_student_reward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.CharField(choices=[('2nd Grade', '2nd Grade'), ('3rd Grade', '3rd Grade'), ('Kindergarten', 'Kindergarten'), ('Pre-K', 'Pre-K'), ('1st Grade', '1st Grade')], max_length=50),
        ),
    ]
