# Generated by Django 4.0.4 on 2022-04-17 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('medium', 'medium'), ('difficult', 'difficult'), ('easy', 'easy')], max_length=20),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='grade',
            field=models.CharField(blank=True, choices=[('Kindergarten', 'Kindergarten'), ('2nd Grage', '2nd Grade'), ('3rd Grage', '3rd Grade'), ('Pre-k', 'Pre-K'), ('1st Grage', '1st Grade')], max_length=50),
        ),
    ]
