# Generated by Django 4.0.4 on 2022-04-21 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_quiz_difficulty_alter_quiz_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='grade',
            field=models.CharField(blank=True, choices=[('Kindergarten', 'Kindergarten'), ('1st Grade', '1st Grade'), ('Pre-K', 'Pre-K'), ('2nd Grade', '2nd Grade'), ('3rd Grade', '3rd Grade')], max_length=50),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='subject',
            field=models.CharField(blank=True, choices=[('Korean', 'Korean'), ('Math', 'Math'), ('Spanish', 'Spanish'), ('English', 'English'), ('Social Studies', 'Social Studies'), ('Science', 'Science')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
