# Generated by Django 4.0.4 on 2022-04-22 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_alter_quiz_difficulty_alter_quiz_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('difficult', 'difficult'), ('medium', 'medium'), ('easy', 'easy')], max_length=20),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='grade',
            field=models.CharField(blank=True, choices=[('2nd Grade', '2nd Grade'), ('3rd Grade', '3rd Grade'), ('Kindergarten', 'Kindergarten'), ('Pre-K', 'Pre-K'), ('1st Grade', '1st Grade')], max_length=50),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='subject',
            field=models.CharField(blank=True, choices=[('Spanish', 'Spanish'), ('Social Studies', 'Social Studies'), ('Science', 'Science'), ('English', 'English'), ('Korean', 'Korean'), ('Math', 'Math')], max_length=20),
        ),
    ]
