# Generated by Django 4.0.4 on 2022-04-27 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_alter_quiz_difficulty_alter_quiz_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='grade',
            field=models.CharField(blank=True, choices=[('1st Grade', '1st Grade'), ('Kindergarten', 'Kindergarten'), ('Pre-K', 'Pre-K'), ('3rd Grade', '3rd Grade'), ('2nd Grade', '2nd Grade')], max_length=50),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='subject',
            field=models.CharField(blank=True, choices=[('Science', 'Science'), ('Korean', 'Korean'), ('Spanish', 'Spanish'), ('Math', 'Math'), ('English', 'English'), ('Social Studies', 'Social Studies')], max_length=20),
        ),
    ]
