# Generated by Django 4.0.4 on 2022-04-27 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_alter_quiz_grade_alter_quiz_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('easy', 'easy'), ('difficult', 'difficult'), ('medium', 'medium')], max_length=20),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='grade',
            field=models.CharField(blank=True, choices=[('Pre-K', 'Pre-K'), ('Kindergarten', 'Kindergarten'), ('2nd Grade', '2nd Grade'), ('1st Grade', '1st Grade'), ('3rd Grade', '3rd Grade')], max_length=50),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='subject',
            field=models.CharField(blank=True, choices=[('Spanish', 'Spanish'), ('English', 'English'), ('Social Studies', 'Social Studies'), ('Korean', 'Korean'), ('Math', 'Math'), ('Science', 'Science')], max_length=20),
        ),
    ]
