# Generated by Django 4.0.4 on 2022-04-27 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_alter_quiz_difficulty_alter_quiz_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('easy', 'easy'), ('difficult', 'difficult'), ('medium', 'medium')], max_length=20),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='grade',
            field=models.CharField(blank=True, choices=[('Pre-K', 'Pre-K'), ('1st Grade', '1st Grade'), ('3rd Grade', '3rd Grade'), ('2nd Grade', '2nd Grade'), ('Kindergarten', 'Kindergarten')], max_length=50),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='subject',
            field=models.CharField(blank=True, choices=[('English', 'English'), ('Korean', 'Korean'), ('Math', 'Math'), ('Science', 'Science'), ('Social Studies', 'Social Studies'), ('Spanish', 'Spanish')], max_length=20),
        ),
    ]
