# Generated by Django 4.0.4 on 2022-04-27 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quiz', '0014_alter_quiz_difficulty_alter_quiz_grade_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('avatar', models.CharField(choices=[('1', 'avatar1')], max_length=50)),
                ('grade', models.CharField(choices=[('Pre-K', 'Pre-K'), ('1st Grade', '1st Grade'), ('3rd Grade', '3rd Grade'), ('2nd Grade', '2nd Grade'), ('Kindergarten', 'Kindergarten')], max_length=50)),
                ('level', models.IntegerField(default=1)),
                ('reward', models.IntegerField(default=0)),
                ('instuctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TakenQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taken_quizzes', to='quiz.quiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='user.student')),
            ],
        ),
    ]
